### ISSUE TITLE
Documentation: HelmChart/values not available?

### ISSUE THREAD

**Issue by dmsolutionz** [DrumSergio/genieacs-docker#10]
Hi There,

It appears some configuration is missing from this repo:

> Please, modify HelmChart/values.yaml file accordingly to make it work inside your cluster. Tested in a K3s cluster with MetalLB Load Balancer.

Could this be added in, or am I missing something?

**Comment by DrumSergio** [comment]
@dmsolutionz Now they have been added. Thanks for the feedback, I wanted to finish it for some time.
