### ISSUE TITLE
Centos7 install failed

### ISSUE THREAD

**Issue by zzzacbbt** [DrumSergio/GenieACS-Docker#2]
![image](https://user-images.githubusercontent.com/38638768/58141118-c08c9500-7c74-11e9-8861-4f876a7f0f53.png)
I use docker-compose to up, but It failed.Do I need to install genieacs first

**Comment by DrumSergio** [comment]
Comment the volumes part in the docker-compose file. That should get rid of the problem. In some systems I don't know but it has a problem when creating volumes...

Sergio Fernández Rubio
(+34) 687 016 994

________________________________
