### ISSUE TITLE
 Problems to start genieacs-gui with Docker

### ISSUE THREAD

**Issue by GLENDIS** [DrumSergio/GenieACS-Docker#4]
Hello Sergio,

Use your project in Docker. Perform the same steps you indicated and I could not raise the genieacs gui. I have not changed the configuration, I'm working with port 7557 on localhost,

Apparently it is a problem with genieacs-nbi.
Sorry but I have not worked with Docker. Can that nbi service be re-run inside the container?

![img1](https://user-images.githubusercontent.com/47321714/60679453-a0e0b300-9e55-11e9-9d9e-5972362b68f5.png)

**Comment by DrumSergio** [comment]
Thank you for posting your issue here.

Please, tell me the exact steps you've done to deploy GenieACS. Have you build it by yourself or have you just downloaded the image from DockerHub?
Could you log in to the container and tell me what's inside `/opt/`? 
Can you post the logs from docker?

**Comment by GLENDIS** [comment]
@DrumSergio 
Download the image of your dockerhub. Apply commands:
docker build -f docker-compose.yml . -t drumsergio/genieacs:1.1.3
docker-compose up -d

`# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                        PORTS                                                                                        NAMES
a0f6deab0d59        mongo-express               "tini -- /docker-e..."   27 hours ago        Restarting (1) 13 hours ago                                                                                                mongo-express
0fd9c695a809        drumsergio/genieacs:1.1.3   "docker-entrypoint..."   27 hours ago        Up 27 hours                   0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
7f0606002345        mongo:4.0                   "docker-entrypoint..."   27 hours ago        Restarting (1) 13 hours ago                                                                                                mongo


Annex files
 **docker-compose.yml**
`[root@genieacs-rhel-new ~]# cat docker-compose.yml
# Use this file to pull GenieACS from DockerHub #

version: "3"
services:
# Dockerfile here: https://github.com/docker-library/mongo/blob/6932ac255d29759af9a74c6931faeb02de0fe53e/4.0/Dockerfile
    mongo:
        image: mongo:4.0
        restart: always
        container_name: "mongo"
        environment:
#            - MONGO_INITDB_ROOT_USERNAME=user
#            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
        volumes:
            - /data/db:/data/db
            - /data/configdb:/data/configdb
        expose:
            - 27017

# Dockerfile here: https://github.com/mongo-express/mongo-express-docker/blob/b089fe7708d9dd619d648a6ec226fe0175b27740/Dockerfile
### WARNING: NOT RECOMMENDED TO RUN THIS SOFTWARE (mongo-express) IN PRODUCTION ENVIRONMENTS ###
    mongo-express:
        image: mongo-express
        container_name: "mongo-express"
        restart: always
        depends_on:
            - 'mongo'
        ports:
            - 8081:8081
        environment:
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=user
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=mongo2018

    genieacs:
        depends_on:
            - 'mongo'
        image: drumsergio/genieacs:1.1.3
        container_name: "genieacs"
        ports:
            - "7547:7547"
            - "7557:7557"
            - "7567:7567"
            - "80:80"
#        volumes:
#            - /opt:/opt
`

**dockerfile.yml**
`# GenieACS v1.1.3 Dockerfile #
##############################

# Dockerfile of node:8-stretch here: https://github.com/nodejs/docker-node/blob/526c6e618300bdda0da4b3159df682cae83e14aa/8/stretch/Dockerfile
FROM node:8-stretch
LABEL maintainer="acsdesk@protonmail.com"

RUN apt-get update && apt-get install -y sudo apt-transport-https apt-utils supervisor
RUN mkdir -p /var/log/supervisor

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn -y
RUN yarn global add genieacs@1.1.3 --exact
RUN ln -s /usr/local/share/.config/yarn/global/node_modules/genieacs /opt

## Change config.json ##
WORKDIR /opt/genieacs/config
RUN openssl genrsa 2048 > cwmp.key
RUN openssl req -new -x509 -days 10000 -key cwmp.key -subj "/C=ES/O=ACSdesk/emailAddress=acsdesk@protonmail.com" > cwmp.crt
RUN cp cwmp.crt nbi.crt && cp cwmp.key nbi.key && cp cwmp.crt fs.crt && cp cwmp.key fs.key
#RUN sed -i 's/mongodb:\/\/127.0.0.1\/genieacs/mongodb:\/\/user:password@127.0.0.1\/genieacs/' config.json
RUN sed -i 's/mongodb:\/\/127.0.0.1\/genieacs/mongodb:\/\/mongo\/genieacs/' config.json
RUN sed -i 's/acs.example.com/acs.local/' config.json
RUN sed -i '0,/false/ s/false/true/' config.json ## Changes first occurence of "false" in SSL on CWMP
#RUN sed -i '8i\ \ "NBI_SSL" : true,' config.json
#RUN sed -i '12i\ \ "FS_SSL" : true,' config.json

# Install GenieACS-GUI #
RUN git clone https://github.com/sstephenson/rbenv.git /root/.rbenv
RUN git clone https://github.com/sstephenson/ruby-build.git /root/.rbenv/plugins/ruby-build
RUN /root/.rbenv/plugins/ruby-build/install.sh
ENV PATH /root/.rbenv/bin:$PATH
RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh # or /etc/profile
RUN echo 'eval "$(rbenv init -)"' >> .bashrc
RUN rbenv install 2.6.2 && rbenv global 2.6.2 && rbenv rehash

RUN echo "gem: --no-document" > ~/.gemrc
WORKDIR /opt/
RUN git clone https://github.com/genieacs/genieacs-gui
WORKDIR /opt/genieacs-gui/config/
RUN cp graphs-sample.json.erb graphs.json.erb && cp index_parameters-sample.yml index_parameters.yml && cp summary_parameters-sample.yml summary_parameters.yml && cp parameters_edit-sample.yml parameters_edit.yml && cp parameter_renderers-sample.yml parameter_renderers.yml && cp roles-sample.yml roles.yml && cp users-sample.yml users.yml

WORKDIR /opt/genieacs-gui/
RUN /root/.rbenv/shims/gem install bundler
RUN /root/.rbenv/shims/bundle
RUN /root/.rbenv/shims/gem install rails
RUN grep -rl "ActiveRecord::Migration$" db | xargs sed -i 's/ActiveRecord::Migration/ActiveRecord::Migration[5.2]/g'
RUN /root/.rbenv/shims/rails db:migrate RAILS_ENV=development

WORKDIR /opt
RUN git clone https://github.com/DrumSergio/genieacs-services
RUN cp genieacs-services/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
`

 **In the container, in /opt/** 
`[root@genieacs-rhel-new GenieACS-Docker]# docker exec -it genieacs /bin/bash
root@0fd9c695a809:/opt# cd /opt/
root@0fd9c695a809:/opt# ls -l
total 1064
lrwxrwxrwx. 1 root root      58 Jun 26 02:14 genieacs -> /usr/local/share/.config/yarn/global/node_modules/genieacs
drwxr-xr-x. 1 root root      38 Jul  4 16:19 genieacs-gui
drwxr-xr-x. 3 root root     186 Jun 26 02:29 genieacs-services
-rw-r--r--. 1 root root 1085206 Jul  5 16:43 supervisord.log
-rw-r--r--. 1 root root       2 Jul  4 16:19 supervisord.pid
drwxr-xr-x. 4 root root      80 Jun 11 08:37 yarn-v1.15.2
`

**Comment by DrumSergio** [comment]
First that I would do is to `docker pull drumsergio/genieacs:1.1.3` because you're building it from source so something new may be breaking. At least my container I know it's working

And the second thing: if you see, the mongo container is restarting. You could post the logs of that container. Also the logs from the genieacs container won't hurt!

**Comment by GLENDIS** [comment]
Hello @DrumSergio, annex records

Steps start of the container, following the steps.
-------------------------------------------------------------------------------------------------------------------
[root@genieacs-rhel-new ~]# **curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    438      0 --:--:--  0:00:01 --:--:--   438
100 11.2M  100 11.2M    0     0  2363k      0  0:00:04  0:00:04 --:--:-- 3358k

[root@genieacs-rhel-new ~]# **curl -L https://raw.githubusercontent.com/docker/compose/1.23.2/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13238  100 13238    0     0  12259      0  0:00:01  0:00:01 --:--:-- 12268

[root@genieacs-rhel-new opt]# **cd /opt && git clone https://github.com/DrumSergio/GenieACS-Docker && cd GenieACS-Docker**
Cloning into 'GenieACS-Docker'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 184 (delta 10), reused 1 (delta 0), pack-reused 162
Receiving objects: 100% (184/184), 39.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (109/109), done.

[root@genieacs-rhel-new GenieACS-Docker]# ll
total 24
-rw-r--r--. 1 root root 1619 Jul  8 10:45 docker-compose.yml
-rw-r--r--. 1 root root 2978 Jul  8 10:45 GenieACS.dockerfile
-rw-r--r--. 1 root root 7652 Jul  8 10:45 LICENSE
-rw-r--r--. 1 root root 3025 Jul  8 10:45 README.md
-rw-r--r--. 1 root root 2271 Jul  8 10:45 Vagrantfile

[root@genieacs-rhel-new GenieACS-Docker]# **docker pull drumsergio/genieacs:1.1.3**
Trying to pull repository registry.access.redhat.com/drumsergio/genieacs ...
Pulling repository registry.access.redhat.com/drumsergio/genieacs
Trying to pull repository docker.io/drumsergio/genieacs ...
1.1.3: Pulling from docker.io/drumsergio/genieacs
e79bb959ec00: Extracting [==================================>                ]  31.2 MB/45.34 MB
d4b7902036fe: Download complete
1b2a72d4e030: Download complete
d54db43011fd: Pull complete
69d473365bb3: Pull complete
6e2490ee2dc8: Pull complete
fc66dfb5c5fd: Pull complete
f0614876c4bf: Pull complete
8da78716e55e: Pull complete
e77fda47ba3b: Pull complete
116fa87eb63b: Pull complete
c9b37d90ea9e: Pull complete
86ab10688428: Pull complete
ea3c0f88a47d: Pull complete
bb1f647178e7: Pull complete
379bd9bf135b: Pull complete
fbea1347b032: Pull complete
ee6639cd2a5e: Pull complete
fd9b5bf42ec8: Pull complete
68051e9f045e: Pull complete
fd77f9324a95: Pull complete
2e4b1f20e05f: Pull complete
a6c5e32312ad: Pull complete
1e4fb0d96883: Pull complete
a931f57578cb: Pull complete
532e3a93506e: Pull complete
779cef86eadf: Pull complete
dc4cf0f2eae1: Pull complete
ecd82651f1b8: Pull complete
77ce59eeaa21: Pull complete
f56c14750d36: Pull complete                                                      .79 MB/69.45 MB
19fca00bc96a: Pull complete
a2a3a5ad50ac: Pull complete
3a8b3b825b45: Pull complete
b5faf30bf5ef: Pull complete
e6cb746b4d4d: Pull complete
Digest: sha256:5a58369eb6c19807fda2dfc79a3d3180fae47e29ba62e254b35056660b13dd76
Status: Downloaded newer image for docker.io/drumsergio/genieacs:1.1.3

[root@genieacs-rhel-new GenieACS-Docker]# **docker ps -a**
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

[root@genieacs-rhel-new GenieACS-Docker]# **docker images**
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
**docker.io/drumsergio/genieacs   1.1.3               2a23f195304e        2 months ago        1.29 GB**

[root@genieacs-rhel-new GenieACS-Docker]# **docker-compose up -d**
Pulling mongo (mongo:4.0)...
Trying to pull repository registry.access.redhat.com/mongo ...
Pulling repository registry.access.redhat.com/mongo
Trying to pull repository docker.io/library/mongo ...
4.0: Pulling from docker.io/library/mongo
35b42117c431: Pull complete
ad9c569a8d98: Pull complete
293b44f45162: Pull complete
0c175077525d: Pull complete
4e73525b52ba: Pull complete
a22695a3f5e9: Pull complete
c5175bcf2977: Pull complete
3e320da07793: Pull complete
01c6db6b2b5a: Pull complete
3bd6e9d03e78: Pull complete
e03dcf51513f: Pull complete
c1956a9e136a: Pull complete
4c35cf22b1d5: Pull complete
Pulling mongo-express (mongo-express:)...
Trying to pull repository registry.access.redhat.com/mongo-express ...
Pulling repository registry.access.redhat.com/mongo-express
Trying to pull repository docker.io/library/mongo-express ...
latest: Pulling from docker.io/library/mongo-express
e7c96db7181b: Pull complete
5b5ce4d3d5f2: Pull complete
ac289eff61bc: Pull complete
28fbd2f3252d: Pull complete
355aefc57dbb: Pull complete
be052a1dc11e: Pull complete
0150ab596ec1: Pull complete
366642a63bb1: Pull complete
Creating mongo ... done
Creating genieacs      ... done
Creating mongo-express ... done

[root@genieacs-rhel-new GenieACS-Docker]# **docker ps -a**
CONTAINER ID        IMAGE                       COMMAND                  CREATED              STATUS                          PORTS                                                                                        NAMES
8f59f96b1347        drumsergio/genieacs:1.1.3   "/usr/bin/supervis..."   About a minute ago   Up 58 seconds                   0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
b7a56aa97804        mongo-express               "tini -- /docker-e..."   About a minute ago   Up 2 seconds                    0.0.0.0:8081->8081/tcp                                                                       mongo-express
15193ff88629        mongo:4.0                   "docker-entrypoint..."   About a minute ago   Restarting (1) 22 seconds ago                                                                                                mongo

[root@genieacs-rhel-new GenieACS-Docker]# **docker ps -a**
CONTAINER ID        IMAGE                       COMMAND                  CREATED              STATUS                          PORTS                                                                                        NAMES
8f59f96b1347        drumsergio/genieacs:1.1.3   "/usr/bin/supervis..."   About a minute ago   Up About a minute               0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
b7a56aa97804        mongo-express               "tini -- /docker-e..."   About a minute ago   Restarting (1) 9 seconds ago                                                                                                 mongo-express
15193ff88629        mongo:4.0                   "docker-entrypoint..."   About a minute ago   Restarting (1) 22 seconds ago                                                                                                

-----------------------------------------------------------------------------------------------------------------

Installed Versions
-----------------------------------------------------------------------------------------------------------------
[root@genieacs-rhel-new /]# **docker version**
Client:
Version:         1.13.1
API version:     1.26
Package version: docker-1.13.1-96.gitb2f74b2.el7.x86_64
Go version:      go1.10.8
Git commit:      b2f74b2/1.13.1
Built:           Tue Apr  2 21:01:07 2019
OS/Arch:         linux/amd64

Server:
Version:         1.13.1
API version:     1.26 (minimum version 1.12)
Package version: docker-1.13.1-96.gitb2f74b2.el7.x86_64
Go version:      go1.10.8
Git commit:      b2f74b2/1.13.1
Built:           Tue Apr  2 21:01:07 2019
OS/Arch:         linux/amd64
Experimental:    false

[root@genieacs-rhel-new /]# **docker info**
Containers: 3
Running: 1
Paused: 0
Stopped: 2
Images: 3
Server Version: 1.13.1
Storage Driver: overlay2
Backing Filesystem: xfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
selinux
Kernel Version: 3.10.0-957.el7.x86_64
Operating System: RHEL
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 1.795 GiB
Name: genieacs-rhel-new
ID: RR5K:HYTY:363H:OSAJ:QPVD:7VKF:5ASA:UGLY:OXKE:6WQZ:UAHU:6CUA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure), registry.fedoraproject.org (secure), quay.io (secure), registry.centos.org (secure), docker.io (secure)

[root@genieacs-rhel-new /]# **rpm -qa |egrep "docker"**
docker-common-1.13.1-96.gitb2f74b2.el7.x86_64
docker-rhel-push-plugin-1.13.1-96.gitb2f74b2.el7.x86_64
docker-1.13.1-96.gitb2f74b2.el7.x86_64
docker-client-1.13.1-96.gitb2f74b2.el7.x86_64

[root@genieacs-rhel-new /]# **docker-compose --version**
docker-compose version 1.23.2, build 1110ad01

-----------------------------------------------------------------------------------------------------------------

Content verification of dockers
-----------------------------------------------------------------------------------------------------------------
[root@genieacs-rhel-new containers]# **pwd**
**/var/lib/docker/containers**
[root@genieacs-rhel-new containers]# ll
total 0
drwx------. 5 root root 168 Jul  8 10:57 15193ff886295465e247659c8c8ffd03eed005db286f386ea09ff1e6f7f44c0a
drwx------. 5 root root 168 Jul  8 10:53 8f59f96b13475e054855789a29c7a24da2962b6f9d4a1b429bb5eff89859556a
drwx------. 5 root root 168 Jul  8 10:58 b7a56aa97804c15e0f5349366e7f6256bcd133283b9677716774f8d5db09a765

[root@genieacs-rhel-new 15193ff886295465e247659c8c8ffd03eed005db286f386ea09ff1e6f7f44c0a]# ll
total 24
drwx------. 2 root root    6 Jul  8 10:53 checkpoints
-rw-r--r--. 1 root root 3540 Jul  8 10:55 config.v2.json
-rw-r--r--. 1 root root 1204 Jul  8 10:55 hostconfig.json
-rw-r--r--. 1 root root   13 Jul  8 10:55 hostname
-rw-r--r--. 1 root root  150 Jul  8 10:55 hosts
-rw-r--r--. 1 root root   61 Jul  8 10:55 resolv.conf
-rw-r--r--. 1 root root   71 Jul  8 10:55 resolv.conf.hash
drwxr-xr-x. 4 root root   63 Jul  8 10:55 secrets
drwx------. 2 root root    6 Jul  8 10:53 shm
[root@genieacs-rhel-new 15193ff886295465e247659c8c8ffd03eed005db286f386ea09ff1e6f7f44c0a]# **cat hostname**
**15193ff88629**

[root@genieacs-rhel-new 8f59f96b13475e054855789a29c7a24da2962b6f9d4a1b429bb5eff89859556a]# ll
total 24
drwx------. 2 root root    6 Jul  8 10:53 checkpoints
-rw-r--r--. 1 root root 3355 Jul  8 10:53 config.v2.json
-rw-r--r--. 1 root root 1316 Jul  8 10:53 hostconfig.json
-rw-r--r--. 1 root root   13 Jul  8 10:53 hostname
-rw-r--r--. 1 root root  174 Jul  8 10:53 hosts
-rw-r--r--. 1 root root   61 Jul  8 10:53 resolv.conf
-rw-r--r--. 1 root root   71 Jul  8 10:53 resolv.conf.hash
drwxr-xr-x. 4 root root   63 Jul  8 10:53 secrets
drwxrwxrwt. 2 root root   40 Jul  8 10:53 shm
[root@genieacs-rhel-new 8f59f96b13475e054855789a29c7a24da2962b6f9d4a1b429bb5eff89859556a]# **cat hostname**
**8f59f96b1347**

[root@genieacs-rhel-new b7a56aa97804c15e0f5349366e7f6256bcd133283b9677716774f8d5db09a765]# ll
total 24
drwx------. 2 root root    6 Jul  8 10:53 checkpoints
-rw-r--r--. 1 root root 3178 Jul  8 10:58 config.v2.json
-rw-r--r--. 1 root root 1191 Jul  8 10:58 hostconfig.json
-rw-r--r--. 1 root root   13 Jul  8 10:58 hostname
-rw-r--r--. 1 root root  150 Jul  8 10:58 hosts
-rw-r--r--. 1 root root   61 Jul  8 10:58 resolv.conf
-rw-r--r--. 1 root root   71 Jul  8 10:58 resolv.conf.hash
drwxr-xr-x. 4 root root   63 Jul  8 10:58 secrets
drwx------. 2 root root    6 Jul  8 10:53 shm
[root@genieacs-rhel-new b7a56aa97804c15e0f5349366e7f6256bcd133283b9677716774f8d5db09a765]# **cat hostname**
**b7a56aa97804**

-----------------------------------------------------------------------------------------------------------------

The services were stopped and started again and the mondoDB containers were restarted after the time elapsed.
-----------------------------------------------------------------------------------------------------------------
[root@genieacs-rhel-new /]# docker stop b7a56aa97804 15193ff88629
b7a56aa97804
15193ff88629
[root@genieacs-rhel-new /]# docker start b7a56aa97804 15193ff88629
b7a56aa97804
15193ff88629
[root@genieacs-rhel-new /]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                  PORTS                                                                                        NAMES
8f59f96b1347        drumsergio/genieacs:1.1.3   "/usr/bin/supervis..."   17 minutes ago      Up 17 minutes           0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
b7a56aa97804        mongo-express               "tini -- /docker-e..."   17 minutes ago      Up 4 seconds            0.0.0.0:8081->8081/tcp                                                                       mongo-express
15193ff88629        mongo:4.0                   "docker-entrypoint..."   17 minutes ago      Up Less than a second   27017/tcp                                                                                    mongo
[root@genieacs-rhel-new /]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                  PORTS                                                                                        NAMES
8f59f96b1347        drumsergio/genieacs:1.1.3   "/usr/bin/supervis..."   17 minutes ago      Up 17 minutes           0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
b7a56aa97804        mongo-express               "tini -- /docker-e..."   17 minutes ago      Up 11 seconds           0.0.0.0:8081->8081/tcp                                                                       mongo-express
15193ff88629        mongo:4.0                   "docker-entrypoint..."   18 minutes ago      Up Less than a second   27017/tcp                                                                                    mongo
[root@genieacs-rhel-new /]#
[root@genieacs-rhel-new /]#
[root@genieacs-rhel-new /]#
[root@genieacs-rhel-new /]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                         PORTS                                                                                        NAMES
8f59f96b1347        drumsergio/genieacs:1.1.3   "/usr/bin/supervis..."   18 minutes ago      Up 18 minutes                  0.0.0.0:80->80/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
b7a56aa97804        mongo-express               "tini -- /docker-e..."   18 minutes ago      Up 27 seconds                  0.0.0.0:8081->8081/tcp                                                                       mongo-express
15193ff88629        mongo:4.0                   "docker-entrypoint..."   18 minutes ago      Restarting (1) 3 seconds ago                                                                                                mongo

-----------------------------------------------------------------------------------------------------------------

**Comment by DrumSergio** [comment]
Solved: CentOS/RHEL installation was failing. Solved in https://github.com/DrumSergio/GenieACS-Docker/commit/68af190e2921c385e59b67cd1fea3bcae5c8404a

**Comment by juanfrancisco-18** [comment]
buenas tardes me pasa esto en ubuntu   que puedo hacer?

**Comment by dierobe** [comment]
I fixed but upgrading NodeJS to latest version

**Comment by juanfrancisco-18** [comment]
> Lo arreglé actualizando NodeJS a la última versión

tengo una consulta perdone la ignorancia,  se supone  que dentro la imagen instala nodeJS?
