### ISSUE TITLE
GenieACS services can't contact MongoDB. What is wrong?

### ISSUE THREAD

**Issue by xrodpim** [DrumSergio/genieacs-docker#5]
Hi.

Today I have run your Docker container for GenieACS. Everything seems to be ok, because I didn't have any problem following the instructions from the dockerhub page. I executed "docker pull drumsergio/genieacs:1.2.0". Then I executed "docker-compose up -d".

My docker composer is version 1.24.0 and my Ubuntu is version 18.04 (Debian 10).
Docker is version 19.03.4

All containers were started and remained running.
However I saw in the genieacs services logs that all these services can't contact the MongoDB. In addiction it was impossible for a local browser access the page in http://localhost:3000. The UI should be in this port, but I get an error when trying to see the web page in such URL. The services is running in the containers and the browser is running in the local host. Such host is where the containers is running too. I suspect that if I solve the MongoDB connection problem I will get success accessing the http://localhost:3000 on local browser.

What should I check to find out the problem?

Some more information about this issue:

Log saw from genieacs services running in the container:
-------------------------------------------------------------------------

2019-11-07T20:15:03.191Z [ERROR] Uncaught exception; pid=14429 exceptionName="MongoNetworkError" exceptionMessage="failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]" exceptionStack="MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/opt/genieacs/node_modules/mongodb-core/lib/topologies/server.js:431:11)\n    at Pool.emit (events.js:198:13)\n    at connect (/opt/genieacs/node_modules/mongodb-core/lib/connection/pool.js:557:14)\n    at makeConnection (/opt/genieacs/node_modules/mongodb-core/lib/connection/connect.js:39:11)\n    at callback (/opt/genieacs/node_modules/mongodb-core/lib/connection/connect.js:261:5)\n    at Socket.err (/opt/genieacs/node_modules/mongodb-core/lib/connection/connect.js:286:7)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)"
2019-11-07T20:15:03.196Z [ERROR] Worker died; pid=14429 exitCode=1

docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
mongo                     4.0                 074a4b5f10cc        6 days ago          416MB
ubuntu                    18.04               775349758637        6 days ago          64.2MB
drumsergio/genieacs-sim   latest              95c972a4d66c        2 months ago        93MB
drumsergio/genieacs       1.2.0               4830ec2c4d34        2 months ago        1.11GB
drumsergio/genieacs       latest              8b8bbbda5f4b        2 months ago        1.11GB
zabbix/zabbix-appliance   ubuntu-3.4-latest   a45a31e38055        12 months ago       751MB

 docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                                                            NAMES
3852105e7498        drumsergio/genieacs-sim     "docker-entrypoint.s…"   2 hours ago         Up About an hour                                                                                                     genieacs-sim
9eded369c0d0        drumsergio/genieacs:1.2.0   "docker-entrypoint.s…"   2 hours ago         Up About an hour    0.0.0.0:3000->3000/tcp, 0.0.0.0:7547->7547/tcp, 0.0.0.0:7557->7557/tcp, 0.0.0.0:7567->7567/tcp   genieacs
2041f6f0b559        mongo:4.0                   "docker-entrypoint.s…"   2 hours ago         Up About an hour    27017/tcp 

Could you help me, please!
Any hint will be very helpful!

Best regards.

Rodrigo Pimenta Carvalho.

**Comment by DrumSergio** [comment]
Hi Rodrigo,

I have just tried the GenieACS v1.2.0 container version again and everything is working as it should. I have even tested it building it from source and it is still working. I uploaded now the image to DockerHub just in case.
Check that mongo is, in fact, running with the command `docker logs mongo`, if not, troubleshoot.
Otherwise, please check the v1.1.3 container version is working for you.

Let me know if that helped to pinpoint the issue.

**Comment by xrodpim** [comment]
Hi. I have repeated everything in another machine, with ubuntu 16.04 and everything is ok.
So, is there some differences between ubuntu 18.04 and 16.04 that I should know before following your instructions for your docker container ?
Thanks.
Best regards.

**Comment by DrumSergio** [comment]
I tried it on my desktop, which runs Ubuntu 18.04 and it is working seamlessly. There should not be any difference, as long as it is running the latest version of Docker.

**Comment by xrodpim** [comment]
Ok. Thank you ! For sure I had done something wrong here.

**Comment by xrodpim** [comment]
Do you intend to continue supporting this docker container image for GenieACS? Can I use such container inside my project. My project is a network manager software for a company from telecommunication market. What should I care about license to use this container? Thanks.

**Comment by DrumSergio** [comment]
This is the license for this project: https://github.com/DrumSergio/genieacs-docker/blob/master/LICENSE
It should not be a problem as long as you mention my project.
And yes, currently I am supporting this source code, and I hope that in the future too, but who knows...
