### ISSUE TITLE
help with https

### ISSUE THREAD

**Issue by felo230** [DrumSergio/genieacs-docker#9]
Hello,

I'm doing an exercise for college and I'm using genieacs. I am very grateful for your work, it is very helpful to me. This is not an ISSUE properly I am trying to implement HTTPS using the following reference information https://github.com/genieacs/genieacs/wiki/GenieACS-SSL but I cannot find the "config /" directory and neither the files mentioned in With this documentation it is possible that they can give me an orientation to use the ACS with HTTPS please.

In the / opt / genieacs directory I only find the following

root @ f54de76d6317: / opt / genieacs # ls
CHANGELOG.md CONTRIBUTING.md LICENSE README.md ava.config.js bin build dist docs ext genieacs.env lib node_modules npm-shrinkwrap.json package.json public test tools tsconfig.json ui

best regards
Felo.

**Comment by DrumSergio** [comment]
Hi Felo, appreciate it.

This is only a build project. For those kind of issues please search/ask here: https://forum.genieacs.com/ they will be happy to assist you (I hope).
I do not have much time available.

Sergio
________________________________
De: felo230 <notifications@github.com>
Enviado: miércoles, 26 de agosto de 2020 0:07
Para: DrumSergio/genieacs-docker <genieacs-docker@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [DrumSergio/genieacs-docker] help with https (#9)


Hello,

I'm doing an exercise for college and I'm using genieacs. I am very grateful for your work, it is very helpful to me. This is not an ISSUE properly I am trying to implement HTTPS using the following reference information https://github.com/genieacs/genieacs/wiki/GenieACS-SSL but I cannot find the "config /" directory and neither the files mentioned in With this documentation it is possible that they can give me an orientation to use the ACS with HTTPS please.

In the / opt / genieacs directory I only find the following

root @ f54de76d6317: / opt / genieacs # ls
CHANGELOG.md CONTRIBUTING.md LICENSE README.md ava.config.js bin build dist docs ext genieacs.env lib node_modules npm-shrinkwrap.json package.json public test tools tsconfig.json ui

best regards
Felo.

**Comment by felo230** [comment]
I understand, thanks Sergio :)
